# Generated by Django 5.2.8 on 2026-01-18 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='authorized_domains',
            field=models.JSONField(blank=True, default=list, help_text='List of domains this user is authorized to perform active exploitation on'),
        ),
    ]
