# Generated by Django 5.2.8 on 2025-12-13 08:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField(max_length=2048)),
                ('domain', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('overall_score', models.IntegerField(blank=True, null=True)),
                ('grade', models.CharField(blank=True, choices=[('A+', 'A+'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('F', 'F')], max_length=2)),
                ('headers_score', models.IntegerField(blank=True, null=True)),
                ('cookies_score', models.IntegerField(blank=True, null=True)),
                ('tls_score', models.IntegerField(blank=True, null=True)),
                ('https_score', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('response_headers', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='scanner_sca_status_bc0197_idx'), models.Index(fields=['created_at'], name='scanner_sca_created_6012ae_idx'), models.Index(fields=['domain'], name='scanner_sca_domain_f4fe4a_idx')],
            },
        ),
        migrations.CreateModel(
            name='Finding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('issue', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('severity', models.CharField(choices=[('CRITICAL', 'Critical'), ('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low'), ('INFO', 'Info')], max_length=10)),
                ('category', models.CharField(choices=[('headers', 'HTTP Headers'), ('cookies', 'Cookies'), ('tls', 'TLS/SSL'), ('https', 'HTTPS Enforcement'), ('info_disclosure', 'Information Disclosure')], max_length=20)),
                ('impact', models.TextField()),
                ('recommendation', models.TextField()),
                ('fix_examples', models.JSONField(default=dict)),
                ('affected_element', models.CharField(blank=True, max_length=255)),
                ('score_impact', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='scanner.scan')),
            ],
            options={
                'ordering': ['-severity', 'category'],
                'indexes': [models.Index(fields=['scan', 'category'], name='scanner_fin_scan_id_84bf11_idx'), models.Index(fields=['severity'], name='scanner_fin_severit_56b0bd_idx')],
            },
        ),
    ]
