# Generated by Django 5.2.8 on 2026-01-17 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0002_scan_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='finding',
            name='confidence',
            field=models.CharField(blank=True, default='HIGH', max_length=20),
        ),
        migrations.AddField(
            model_name='finding',
            name='evidence',
            field=models.TextField(blank=True, help_text='Raw evidence data (e.g. log output)'),
        ),
        migrations.AddField(
            model_name='finding',
            name='poc',
            field=models.TextField(blank=True, help_text='Proof of Concept command or script'),
        ),
        migrations.AlterField(
            model_name='finding',
            name='affected_element',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='finding',
            name='category',
            field=models.CharField(choices=[('headers', 'HTTP Headers'), ('cookies', 'Cookies'), ('tls', 'TLS/SSL'), ('https', 'HTTPS Enforcement'), ('info_disclosure', 'Information Disclosure'), ('recon', 'Reconnaissance'), ('waf', 'WAF Detection'), ('malware', 'Malware & Phishing'), ('threat_intel', 'Threat Intelligence'), ('ai_analysis', 'AI Analysis')], max_length=20),
        ),
    ]
